# References:
# https://devcenter.heroku.com/articles/container-registry-and-runtime
# https://enlear.academy/how-to-deploy-a-dockerized-web-app-to-heroku-using-the-github-actions-f16c00b19621

# Your workflow name.
name: Deploy to heroku.

# Run workflow on every push to master branch.
on:
  push:
    branches: [master]

# Set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

# Your workflows jobs.
jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

      # Add environment variable to .env
      # - name: "Configure Environment"
      #   run: echo "NODE_ENV=production" >> .env

      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Heroku Container Registry.
      - name: Login to Heroku Container registry
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      # Push docker image to Heroku Container Registry.
      - name: Building and pushing image
        run: heroku container:push -a $HEROKU_APP_NAME web

      # Release the Docker image to Heroku Container Registry.
      - name: Release app
        run: 
          heroku container:release -a $HEROKU_APP_NAME web
